// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Talos
{
    [TalosResourceType("talos:index:ClusterConfig")]
    public partial class ClusterConfig : Pulumi.ComponentResource
    {
        /// <summary>
        /// Provides control plane specific configuration options.
        /// </summary>
        [Output("configYAML")]
        public Output<string> ConfigYAML { get; private set; } = null!;


        /// <summary>
        /// Create a ClusterConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClusterConfig(string name, ClusterConfigArgs args, ComponentResourceOptions? options = null)
            : base("talos:index:ClusterConfig", name, args ?? new ClusterConfigArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ClusterConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configures the cluster's name.
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        /// <summary>
        /// Provides control plane specific configuration options.
        /// </summary>
        [Input("controlPlaneConfig", required: true)]
        public Input<Inputs.ControlPlaneConfigArgs> ControlPlaneConfig { get; set; } = null!;

        public ClusterConfigArgs()
        {
        }
    }
}
