// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package talos

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ControlPlaneConfig struct {
	Endpoint           *string `pulumi:"endpoint"`
	LocalAPIServerPort *int    `pulumi:"localAPIServerPort"`
}

// ControlPlaneConfigInput is an input type that accepts ControlPlaneConfigArgs and ControlPlaneConfigOutput values.
// You can construct a concrete instance of `ControlPlaneConfigInput` via:
//
//          ControlPlaneConfigArgs{...}
type ControlPlaneConfigInput interface {
	pulumi.Input

	ToControlPlaneConfigOutput() ControlPlaneConfigOutput
	ToControlPlaneConfigOutputWithContext(context.Context) ControlPlaneConfigOutput
}

type ControlPlaneConfigArgs struct {
	Endpoint           pulumi.StringPtrInput `pulumi:"endpoint"`
	LocalAPIServerPort pulumi.IntPtrInput    `pulumi:"localAPIServerPort"`
}

func (ControlPlaneConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ControlPlaneConfig)(nil)).Elem()
}

func (i ControlPlaneConfigArgs) ToControlPlaneConfigOutput() ControlPlaneConfigOutput {
	return i.ToControlPlaneConfigOutputWithContext(context.Background())
}

func (i ControlPlaneConfigArgs) ToControlPlaneConfigOutputWithContext(ctx context.Context) ControlPlaneConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ControlPlaneConfigOutput)
}

type ControlPlaneConfigOutput struct{ *pulumi.OutputState }

func (ControlPlaneConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ControlPlaneConfig)(nil)).Elem()
}

func (o ControlPlaneConfigOutput) ToControlPlaneConfigOutput() ControlPlaneConfigOutput {
	return o
}

func (o ControlPlaneConfigOutput) ToControlPlaneConfigOutputWithContext(ctx context.Context) ControlPlaneConfigOutput {
	return o
}

func (o ControlPlaneConfigOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ControlPlaneConfig) *string { return v.Endpoint }).(pulumi.StringPtrOutput)
}

func (o ControlPlaneConfigOutput) LocalAPIServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ControlPlaneConfig) *int { return v.LocalAPIServerPort }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ControlPlaneConfigInput)(nil)).Elem(), ControlPlaneConfigArgs{})
	pulumi.RegisterOutputType(ControlPlaneConfigOutput{})
}
